//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tender
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tender()
        {
            this.UserSavedTenders = new HashSet<UserSavedTender>();
        }
    
        public long Id { get; set; }
        public long TenderTypeId { get; set; }
        public Nullable<System.DateTime> OpeningDay { get; set; }
        public string Address { get; set; }
        public System.DateTime PostedOn { get; set; }
        public string TenderTitle { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> ClosingDay { get; set; }
        public long NewsPaperId { get; set; }
        public System.DateTime NewsPaperPublishDate { get; set; }
    
        public virtual NewsPaper NewsPaper { get; set; }
        public virtual TenderType TenderType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSavedTender> UserSavedTenders { get; set; }
    }
}
